version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: survey-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: survey_platform
      MYSQL_USER: survey_user
      MYSQL_PASSWORD: survey_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - survey-network
    command: --default-authentication-plugin=mysql_native_password

  # 主应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: survey-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://survey_user:survey_password@mysql:3306/survey_platform
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - mysql
    networks:
      - survey-network

volumes:
  mysql_data:

networks:
  survey-network:
    driver: bridge 